[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/api/wind"
  to   = "/.netlify/functions/wind"
  status = 200
  force = true

[[redirects]]
  from = "/api/hourly-wind"
  to   = "/.netlify/functions/hourly-wind"
  status = 200
  force = true
